### ISSUE TITLE
steroids-js 3.5.13 breaks supersonic.data.channel().publish() 

### ISSUE THREAD

**Issue by dantabel** [AppGyver/steroids#1020]
The latest update of steroids 3.5.13 breaks `supersonic.data.channel().publish()`. I rolled back to 3.5.12 and it works fine again.

I get error: `Error: Failed to execute 'postMessage' on 'Window': An object could not be cloned.`

**Comment by garrettlangley** [comment]
@dantabel this is a dup of #1019 

hearing crickets from AppGyver team about introducing this major of a bug

**Comment by yoka** [comment]
@dantabel steroids-js no longer hijacks window.postMessage completely, but delegates it to original browser postMessage function. Your error comes from native browser function and it happens when you try to post incorrect data. For example if you're posting object that has functions as key values. 

in https://github.com/AppGyver/steroids-js/commit/ff0d146ed0fe4f241df9f5c1083d037fbd08ca83 commit there is a fix that native postMessage no longer throws (so that the code execution will not halt for people who have passed "incorrect" values to postMessage).

This has now been fixed. Thank you for reporting!
