### ISSUE TITLE
window.postMessage fires the message event twice after upgrading to steroids 4.1.16

### ISSUE THREAD

**Issue by ukrit-himakoon** [AppGyver/steroids#1033]
The calling source code is in the example below:
```
        var message = {
        action: "alert",
        text: "Alert message!"
        };
            window.postMessage(message, "*");
            return;
        }
```
Here's the activity logs:
![invoketwice](https://cloud.githubusercontent.com/assets/3422247/9489660/bec6d100-4c0c-11e5-9f6b-9439bc90aa4c.png)

**Comment by satusuuronen** [comment]
Does this happen both on iOS and Android?

**Comment by ukrit-himakoon** [comment]
Yes, I currently experience this on both iOS and Android

**Comment by wiwat-tharateeraparb** [comment]
Something to do with steroids.js 3.5.14. It does not happen with 3.5.11 though.

**Comment by wiwat-tharateeraparb** [comment]
Here it is https://github.com/wiwat-tharateeraparb/bug1033. Calling `window.postMessage()` and `window.addEventListener()` got two messages.

**Comment by satusuuronen** [comment]
Thanks for the repro! I changed the title accordingly.

**Comment by sunny061** [comment]
Any updates on this?

**Comment by wiwat-tharateeraparb** [comment]
one month has passed.

**Comment by gerarrd** [comment]
I am having the same problem now, any updates on this one?

**Comment by rabbitfufu** [comment]
+1

**Comment by wiwat-tharateeraparb** [comment]
4.1.20 still has this bug on iOS 8.4 simulator. Crashed entirely upon start on iOS 9.0 simulator.

**Comment by wiwat-tharateeraparb** [comment]
Tested with 4.1.21 and it still has this bug.

**Comment by Sampax** [comment]
The duplicate message is only received in the view that sends the initial message, and is a side-effect of a fix done in [steroids-js 3.5.13](https://github.com/AppGyver/steroids-js/blob/next/CHANGELOG.md#3513-2015-08-13) to ensure all postMessages are passed through to the window. 

If you need to listen to messages in the originating view, the superfluous postMessage can be distinguished through the different origin that the message has (see pic below). Steroids sets the postMessage origin to be `""` (empty string).

![web_inspector_ _simulator_ _appgyver_ _background_html_and_web_inspector_ _simulator_ _appgyver_ _localhost_ _bug1033_html](https://cloud.githubusercontent.com/assets/1540411/10605624/9b300500-7735-11e5-8842-fc66b7171e38.png)

Realistically, this does not seem like an urgent issue and will probably not be fixed in the near future. But if it's causing you problems that I didn't catch, we can re-evaluate the situation.

**Comment by wiwat-tharateeraparb** [comment]
Good. Thanks. This works.

**Comment by Sampax** [comment]
Re-opening the issue until it is conclusively solved (no duplicate messages anywhere).
