### ISSUE TITLE
Suggestion: Improve new view performance

### ISSUE THREAD

**Issue by davistan** [AppGyver/steroids#1049]
Since that creating new view consumes time to initialize the webview instance and loading the html, I had an idea to improve the speed of showing the new view.

Steroids can always have an empty webview instance on hand, so when the API to create new view is called, it can use the extra empty webview and be displayed faster as now the webview instance creation can be skipped.

Hope this is a valid suggestion and can be added to the roadmap.

**Comment by harsaharsa** [comment]
Thanks for the suggestion! I'll check with the iOS and Android guys if this'd make sense.

**Comment by pre** [comment]
Have you tried using a preloaded webview? Preloading a webview will "prewarm" a particular webview with an id and it will be instantly accessible when you call `layers.push()` for it.  The downside is that you can't have too many preloaded webviews, since each view will consume memory. 

If using a preload doesn't work for you, please comment here to reopen the issue.

**Comment by davistan** [comment]
Thanks for the reply.

Yes, we can preload manually and once we dispose the view, we need to manually preload it again, etc. If the preloading can be done by Steroids, it can greatly reduce the complexity and improved performance.

However, I suggest that to invoke this feature manually as an API (e.g. supersonic.ui.enableViewCache).

Then the Steroids will load an empty WebView behind the scene. Does the creation of WebView is blocking or non-blocking to the UI thread?

As the title implies, this is just a suggestion where to make Steroids more developer-friendly.
Do not feel obligated to add this feature if this is too much work.

Thanks again!
