### ISSUE TITLE
iOS navbar + tabs. If no navbar on first tab, goto new view, press first tab, empty navbar appears

### ISSUE THREAD

**Issue by poppahorse** [AppGyver/steroids#1100]
Have recreated this in the kitchensink, just remove the `super-navbar` from the index.html in the first tabs view. Have forked it here - https://github.com/poppahorse/supersonic-kitchensink
### Symptoms

Empty / false tab bar appears, and persists onto other views.

iOS only, as using the tab bar to go back isn't typical android behaviour (would use soft back, or navbar back)
### Recreate it by
1. On first tab (has to have no navbar), go to another view with that tab stack
2. Don't press back, instead press the first tab, which emulates back
3. Even though no navbar, an empty navbar appears - [screenshot](http://antimac.meloncreative.co.uk/misc/temp_images/IMG_0004.PNG)
4. Go to another view in same tab stack, press back in navbar - [screenshot](http://antimac.meloncreative.co.uk/misc/temp_images/IMG_0005.PNG)
5. View doesn't go back, the proper navbar goes, but the empty navbar remains - [screenshot](http://antimac.meloncreative.co.uk/misc/temp_images/IMG_0006.PNG)

Have made it hide the navbar on whenVisible, but navbar still persists on next view

```
supersonic.ui.views.current.whenVisible( function() {
    supersonic.ui.navigationBar.hide().then( function() {});
});
```

**Comment by harsaharsa** [comment]
Thanks for the detailed bug report! The tab bar tap-to-go-to-root is a native iOS functionality that is automatically enabled – sounds like the code that's being executed brings up the navigation bar automatically, and then leaves it haunting.

As a potentially more reliable (if hacky) workaround, the [supersonic.ui.tabs.whenDidChange](http://docs.appgyver.com/supersonic/api-reference/stable/supersonic/ui/tabs/whendidchange/) event handler could be used to hide the navbar instead of the whenVisible handler.

**Comment by 123AndGo** [comment]
I guess this issue is related with this one: #1061 
No solution so far. We are still stuck with iOS runtime v4.0.6 builds, which didn't have this bug.
