### ISSUE TITLE
Android 8.0

### ISSUE THREAD

**Issue by lanceomni** [AppGyver/steroids#1141]
On August 1, Google Play requires new apps to target at least Android 8.0 (API level 26). But in appgyver build service, we can't.  Any idea when we will be able to?

**Comment by Jasphine** [comment]
Also, on November 2018 onward, Google Play requires update apps to target at least API level 26, but the maximum 'Minimum SDK version' we can select in Appgyver build service is 21 only. Any idea when API level 26 will be available?

**Comment by EdwinRikkers** [comment]
Please can this be fixed in the Cloud Service? Because from November 2018 we can't update our apps in de Android Play Store anymore because of the API level.

**Comment by harsaharsa** [comment]
We sent the following mail to people who had built Android builds in the Build Service, but I'll copypaste it here too. Sorry for the slow flow of information here.

**SUPERSONIC ANDROID SUNSET**

AppGyver has always been in the business of making app creation ever faster and more accessible to everyone. For a while now, this has meant focusing on our Composer platform, with Steroids and Supersonic receiving less attention.

As we near the launch of Composer 3, and with it, our brand-new, React Native based mobile runtime, the existing Android client is increasingly legacy technology.

Combined with changes in Google Play submission policy, and Intel having shut down the Crosswalk project [over a year ago](https://crosswalk-project.org/blog/crosswalk-final-release.html), we are officially sunsetting Supersonic Android.

**THE ISSUE**

From November 2018 onwards, Google will not allow existing apps to be updated if the new binary build does not target at least Android 8.0 (API level 26). Already, submission of completely new apps built with older SDKs is prevented.

See the [Google Play Developer portal article](https://developer.android.com/distribute/best-practices/develop/target-sdk) for more information.

AppGyver utilizes Intel's Crosswalk project to deliver WebViews that function identically, regardless of the underlying Android OS version. With evergreen WebViews in modern Android OS versions, this is not a problem anymore, but back when we were first developing Steroids and Supersonic, OS fragmentation was a huge issue for hybrid apps and Crosswalk was a great solution for the problem.

Unfortunately, Crosswalk uses legacy Android APIs that prevent projects using it from targeting API level 26. The legacy API calls in question are extremely deep in Crosswalk's internal workings. There is no viable way to get rid of them, or upgrade them to a newer version, as that would entail reworking the massive Crosswalk codebase in fundamental ways. Crosswalk is also deeply ingrained within the Supersonic native Android client, and refactoring Crosswalk out of the project would essentially require a full rewrite. As the Crosswalk project has been long abandoned by Intel, there's no open source community to help out either.

While few technical challenges are insurmountable, and AppGyver has always been in the habit of building impossible things, putting in the effort to support our legacy Android client is no longer viable in the light of the above facts.

The immediate effect to prepare for is that apps built with Supersonic cannot be published on Google Play, and existing apps cannot be updated after the beginning of November. That said, we'll keep our Build Service up and running for the time being, and apps built for e.g. internal enterprise distribution remain unaffected. However, the sunset decision means the legacy Android client will be provided as-is, with no further updates planned.

**GOING FORWARD**

Composer 3, our biggest release yet, is scheduled for launch before the end of the year. It will combine the professional-grade visual tooling with full code-level extendibility: a true visual IDE.

Due to the fundamentally different nature of the Composer 3 platform, there's no direct migration path for existing projects. That said, logic in Composer 3 is still JavaScript based, so porting the functionalities over should be straightforward.

If you want to discuss possibilities of an AppGyver-assisted migration of your Steroids/Supersonic Android app to the Composer 3 platform, let us know and we can explore the available options with you.

Best,
the AppGyver team
https://www.appgyver.com

**Comment by rAthur** [comment]
Hi @harsaharsa , 

I missed that news and now I'm in trouble as I absolutely need to update a client's Supersonic app by the end of the week. 

I understand the issue wit Intel and Crosswalk, but couldn't you make Platform Webview work? 

Thanks a lot,

**Comment by rAthur** [comment]
I found a solution that allow me to get the app accepted on the Play Store, but it will crash on Android 8. 

I generated the usual APK, then I opened it using **[APK Icon Editor](https://kefir500.github.io/apk-icon-editor/)** which is a free software that is made to change app's icons from the final APK and regenerate a new signed APK, that also allow you to edit a few properties including the Target SDK (_targetSdkVersion_ in the Android Manifest). 

All I had to do was to import my APK in **APK Icon Editor**, go in the **Properties** tab, change the **Target SDK** value to 26 (be sure to keep a lower value in the **Minimum SDK** field as it's the one telling what Android version can actually instal your app, if it's high then older phones won't have access to your app), and click on **Pack APK** to generate a new signed APK that is accepted by the Play Store!

I then tested to install my app from the Play Store on a Android 6 with success but as we could expect it crashes on Android 8, the edited Target SDK number dupes the Play Store so it lets the APK in, but in the end it hasn't been built with Android 8 capabilities, so it won't work on that version.

**Comment by RHinderiks** [comment]
@rAthur We're running into this issue however our app works fine on android 8 when building it with api level 21 (which as you know is not accepted by google anymore) So i used your trick to target 26 instead but then it wont work on Android 8 anymore. How come the app works fine on android 8 building with api level 21 but then changing the api level it wont even start ?

**Comment by RHinderiks** [comment]
@rAthur That makes sense, do you know if the people of appgyver have released a transitioning manual or something. To bring your app to their new platform as fast as possible. It would only be temporary since we're building a new app and definitely not using any appgyver related software ever again.

**Comment by rAthur** [comment]
@RHinderiks I don't know if a transition guide has been made, I don't think so because they are working on a new version of Composer that would rely on React Native which is a completely different platform than Cordova.

**Comment by Jasphine** [comment]
Hey guys,

I hope this(https://cordova.apache.org/docs/en/latest/guide/cli/index.html) help and solve your problem.
