### ISSUE TITLE
initialView.dismiss() shows the whole app directory structure.

### ISSUE THREAD

**Issue by atif-kht** [AppGyver/steroids#775]
I have set the initialView in structure.coffee like this:

initialView:
    id: "initialView"
    location: "login#login"

On Login screen, I check for the valid user and then opens another view based on the userID. On that new screen the below function does not work for me:

supersonic.ui.drawers.open();

Before introducing initialView, this function was working fine for me. So, I thought of dismissing the initialView before opening a new view. So I did the following:

steroids.initialView.dismiss({ autohide: false });
var view = new supersonic.ui.View("admin#home-page");
supersonic.ui.layers.push(view);

But this opens the directory structure :( Any idea?

**Comment by atif-kht** [comment]
It looks like, we have to wait at least a day to get a reply :( Mean if you are on tight deadline, do not choose this framework at all !

**Comment by pre** [comment]
Please post your full code example. 

I assume that the code you pasted above is all executed in the same WebView (in Initial View), right ?

This naturally won't work if you pause for a second to think what's happening:

1) Dismissing InitialView will close the WebView which is showing you the initial view
2) The Javascript runtime for this webview will close
3) Code you run after dismiss() will not get executed.

Define the view hierarchy (either tabs or without them) in structure.coffee. The view hierarchy will be opened after initial view is dismissed. If you later show the initial view again, it will (loglcally) dismiss *all* the other views you have open. That makes it very efficient for eg. login, because you won't have any old WebViews with old cache remaining if you eg. change the user account.

PS. In the future, please ask questions related usage in the [forums](https://forums.appgyver.com). Github issues is for bug reports, so you're not guaranteed an answer. Thanks!

**Comment by atif-kht** [comment]
No, I am doing the following:

1. On successfull login, store session value in localStorage and push home page layer code

var view = new supersonic.ui.View("admin#home-page");
supersonic.ui.layers.push(view);

2. On Home-page, I am calling this code to dismiss the initialView:
steroids.initialView.dismiss({ autohide: false });

But am not able to get the home page screen, it loads the directory structure :( that's why I pushed this question here, as I believe this is a bug.

**Comment by atif-kht** [comment]
Furthermore, I am not using either preload or tabs from structure.coffee?

**Comment by pre** [comment]
What do you mean by "the directory structure" ? 

Did I understand correctly: You are calling `layers.push()` before you have called `initialView.dismiss()` ?  This will push the layer *inside* the initial view, so when you dismiss the initial view later, you view is in the wrong layer stack.

Dismiss the initial first, then your Steroids application will automatically create the views according to your `structure.coffee`.
