### ISSUE TITLE
Deploy doesn't have options to select which Grunt task

### ISSUE THREAD

**Issue by mikey0000** [AppGyver/steroids#779]
At the moment on the project I am working on I need to point deploy to a different grunt task than default. I am looking into producing a pull request but for now I'm opening an issue on it.

**Comment by pre** [comment]
Please clarify and then reopen this issue. I don't understand neither what would need to be done for this issue to be fixed.

**Comment by cherryleafroad** [comment]
I believe that the user means that in the default GruntFile.js created when you run `steroids create` only has one Grunt task in the file, `default`. I believe that he would like to use a different Grunt task, such as `production` when deploying the app.  I also could use such a feature as well, because I have some things that I would like to remove when building and deploying the app, such as debug code. It's a bit of a hassle to have to uncomment some of the production tasks for the default Grunt task for when I build it.
