### ISSUE TITLE
steroids.openURL on Android returns Undefined and not working

### ISSUE THREAD

**Issue by roberto-robles** [AppGyver/steroids#790]
Tested on Android Lollipop with latest Scanner app available and using Adhoc build 4.0.4 and 4.0.5-edge2

**Comment by pre** [comment]
Could `<button onclick="window.open('http://example.com', '_system')">Click here</button>` be workaround?

**Comment by harsaharsa** [comment]
Tested with latest Google Play scanner and 4.0.5-edge9 Ad Hoc build, works on both. Closing until further repro appears (e.g. APK where `steroids.openURL("http://www.google.com")` is not working). Returning "undefined" in console is expected, since the result of the call is handled via callbacks, not by the immediate return value of the function.
