### ISSUE TITLE
Supersonic.ui.layers.replace doesn't return a resolved status when successful

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#824]
From [forums](https://forums.appgyver.com/#!/steroids-bugs:supersonicuilayersreplac):
> When i initiate a supersonic.ui.layers.replace(view).then(), the function properly works but the resolved status never seems to be returned. My debugger shows it is called, then calls an find function, which is resolved and then just stops.
The thing is, the replace is properly handled and my view is now my new layer stack.
I've also tested it with an onSuccess callback, which isn't called either. I assume this is a bug in the supersonic API? Any feedback would be appreciated!
Some code below to reproduce the situation:
~~~
var replacementView = new supersonic.ui.View({
    location: "common#replacementView",
    id: "replacementView"
});
replacementView.start().then(function () {
    supersonic.ui.layers.replace(replacementView).then(function () {
       alert("replace succesfully handled!");
    };
});;
~~~

**Comment by pentateu** [comment]
in iOS by the time the success handler is called in the native code.. the web view is already dead.. because it was discarded by the replace API.. so the code:
```
{
       alert("replace succesfully handled!");
    }```
is never executed.

if this code is executed in a web view that was also preloaded (so it is not removed from memory by the replace API) the callback will be called successfully.
