### ISSUE TITLE
TestFlight does not accept IPA file (error: Missing Code Signing Certificate)

### ISSUE THREAD

**Issue by justincolangelo** [AppGyver/steroids#847]
This isn't necessarily related to Steroids, but is part of the test process. I followed this guide to test push notifications:

    http://docs.appgyver.com/tooling/push-notifications/ios/

I created a basic application, added some of the code to register push notifications, published to the cloud, and created .p12 and .mobileprovision files based on the guide. When I get my .ipa file from the build service and try to submit through Application Loader (iTunes Connect site recommendation) I get this error every time:

    Error ITMS-9000 Invalid provisioning profile. The provisioning profile included in the bundle [app name here] is invalid. Missing code-signing certificate

I wasn't able to find any issues related to this on github probably because it isn't a Steroids issue (previously with TestFlight the .ipa files installed without issue). The information I am finding about this issue online is not clear to me. Does anyone have some suggestion for resolving this issue?

**Comment by pre** [comment]
The new TestFlight no longer accepts builds signed with the developer certificate. You're trying to upload an `ipa` file which has been built with a developer certificate.

You will need to upload a `zip` file, that is, create an App Store build from the Build Service. 
That build will be signed with your distribution certificate. 

Notice that builds with distribution certificate cannot be opened in Safari Debugger. If you need to deliver debug builds, you'll need to use another service such as TestFairy.

The good thing about the new TestFlight is that it helps your QA. You can open in your device the *exactly* same application which you will later submit to App Store (via TestFlight). Previously you had to create two *different* builds since you weren't able to run the App Store build in your device in any way.

Please report here if this fixes your issue.

**Comment by justincolangelo** [comment]
Thank you for that. This worked for me. I also started using TestFairy.

**Comment by harsaharsa** [comment]
Closing this since it's not really an issue, just the state of things with Apple!
