### ISSUE TITLE
Minified superonic.js, steroids-js.js, cordova.js

### ISSUE THREAD

**Issue by albertwchang** [AppGyver/steroids#871]
Does it make sense to include minified versions of these files in the Steroids/Supersonic distributions?

**Comment by chrisnicola** [comment]
I have not been bothering to minify anything. I don't really see much point since they are included locally in the distribution.

**Comment by albertwchang** [comment]
In that case, i must be missing something.  Every time I run "steroids update", "bower update", or "bower install", both steroids-js and supersonic folder don't come with their minified version.  Of course, I can simply run Uglify or setup my own grunt task to minify.

**Comment by Leeds-eBooks** [comment]
I think @chrisnicola must have meant that there's no point minifying because the *unminified* files are included in the distribution and therefore there are no http requests for these files, making minification much less important. The only possible benefit of minification would be to reduce the overall app size, which when we're talking about a matter of KB is not going to make much difference.

**Comment by albertwchang** [comment]
Thanks for the responses, Leeds and Chrisnicola.  Point taken, and understood.  Please close
