### ISSUE TITLE
supersonic.ui.dialog.confirm callback fires on second time 

### ISSUE THREAD

**Issue by JugnuPathak** [AppGyver/steroids#947]
I'm using  supersonic.ui.dialog.confirm to take user confirmation on particular action. But sometimes  conformation button callback doesn't fire one first time , but its fire when again   supersonic.ui.dialog.confirm is called

Its look like a cordova bug according following discussion on stack overflow: http://stackoverflow.com/questions/22410659/cordova-on-android-navigator-notification-confirm-callbacks-stuck-in-queue

According to above link this issue has been solved in cordova 3.6.0; as per my knowledge appgyver's current cordova version is 3.5.1. So how can upgrade my cordova version for appgyver or appgyver has some solution /workaround?

**Comment by harsaharsa** [comment]
Backporting the 3.6.0 fixes are on the backlog, see https://github.com/AppGyver/steroids/issues/772#issuecomment-105693825 for more details on the issue. Full Cordova upgrade to Android 4.0 is coming up at some point, too.

**Comment by JugnuPathak** [comment]
what should i do to get it working? Any workaround? @harsaharsa

**Comment by JugnuPathak** [comment]
@harsaharsa  Good job !!!!!  Its now working in scanner builds 4.0.6 edge-2.

But still some pages are showing that famous error :  "deviceready has not fired after 5 seconds" .

Also i got this on my rootview : "View http://localhost/app/myapp/firstpage.html is not started, wont register channel"

**Comment by satusuuronen** [comment]
If you have multiple preloads, that seems to slow down deviceready. Is it possible that it just fires late, like later than 5 s? Does anything actually break when you see this error? Please respond to #772, I am closing this issue since it's a duplicate of that.

As for the log error, it's due to differences in param handling between started and non-started views and it's nothing to worry about. The message is confusing and we should remove it. Thanks for bringing it up!
